name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2" # Specify the Node.js version you need

      - name: Install Newman
        run: npm install -g newman newman-reporter-allure

      - name: Create output directory
      run: mkdir -p output/allure-results

      - name: Run API tests
        run: |
          newman run Tests/API-Testing.postman_collection.json \
            -e Env/Development.postman_environment.json \
            --reporters cli,allure,json \
            --reporter-allure-export output/allure-results \
            --reporter-json-export output/newman-results.json

      - name: List output directory contents
        run: ls -R output

      - name: Archive Allure Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: output/allure-results

      - name: Archive Newman Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-results
          path: output/newman-results.json
